/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.toolkit.toolers.Dialog;

import com.toolkit.toolers.BaseFrame;
import com.toolkit.toolers.Services.DirectoryServices;
import com.toolkit.toolers.Services.GitServices;
import java.io.File;
import java.util.concurrent.Future;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import jdk.jfr.Percentage;
import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.lib.ProgressMonitor;
import org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author Ariel
 */
public class CreateRepoPanel extends javax.swing.JPanel {

    BaseFrame baseFrame;

    /**
     * Creates new form CreateRepoPanel
     */
    public CreateRepoPanel(BaseFrame baseFrame) {
        initComponents();
        this.baseFrame = baseFrame;
        
        PromptSupport.setPrompt("Repo Name...", RepoNameTxtField);
         PromptSupport.setPrompt("Command...", CommandTxtField);
          PromptSupport.setPrompt("Token...", TokenTxtField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RepoNameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CommandTxtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        GitProgressBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        TokenTxtField = new javax.swing.JTextField();

        jLabel1.setText("Create Repo");

        RepoNameTxtField.addActionListener(this::RepoNameTxtFieldActionPerformed);

        jLabel2.setText("Repository Name:");

        jLabel3.setText("Git clone command");

        CommandTxtField.addActionListener(this::CommandTxtFieldActionPerformed);

        jButton1.setText("Add");
        jButton1.setToolTipText("");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        GitProgressBar.setBackground(new java.awt.Color(169, 211, 255));
        GitProgressBar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        GitProgressBar.setToolTipText("");
        GitProgressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GitProgressBar.addChangeListener(this::GitProgressBarStateChanged);

        jLabel4.setText("If private please add token");

        TokenTxtField.addActionListener(this::TokenTxtFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GitProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(RepoNameTxtField)
                            .addComponent(CommandTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(TokenTxtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepoNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommandTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(TokenTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GitProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RepoNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepoNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepoNameTxtFieldActionPerformed

    private void CommandTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommandTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommandTxtFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Repo = RepoNameTxtField.getText();
        String gitUrl = CommandTxtField.getText();
        String Token = TokenTxtField.getText();

        GitServices git = new GitServices(Repo);

        SwingWorker<Void, Void> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {

                ProgressMonitor monitor = new ProgressMonitor() {

                    private int totalTasks;
                    private int completedTasks;
                    private String compObject = "";
                    private int totalSubUnit;
                    private String titles;
                    private double Percentage;

                    @Override
                    public void start(int totalTasks) {
                        this.totalTasks = totalTasks;
                        this.completedTasks = 0;
                        GitProgressBar.setValue(this.completedTasks);
                        GitProgressBar.setStringPainted(true);
                    }

                    @Override
                    public void beginTask(String title, int totalWork) {
                        compObject = title; //name in progress bar

                        totalSubUnit = totalWork;
//                        System.out.println("Task: " + title + " (" + totalWork + " units)");
                        completedTasks = 0;

                        titles = title;

                    }

                    @Override
                    public void update(int completed) {

                        completedTasks += completed;

                        if (completedTasks != 0 && totalSubUnit != 0) {
                            Percentage = ((double) completedTasks / totalSubUnit) * 100;

                            javax.swing.SwingUtilities.invokeLater(() -> {
                                GitProgressBar.setValue((int) Percentage);
                                GitProgressBar.setString(titles);
                            });
                        }

//                        System.out.println("Progress: " + completedTasks + "/" + totalSubUnit);
//                        System.out.println((int) Percentage);
                    }

                    @Override
                    public void endTask() {
                    }

                    @Override
                    public boolean isCancelled() {
                        return false; // Return true if you want to cancel the operation
                    }

                    @Override
                    public void showDuration(boolean bln) {
                    }
                };

                try (Git result = Git.cloneRepository()
                        .setURI(gitUrl)
                        .setDirectory(new File(Repo))
                        .setProgressMonitor(monitor)
                        .setCredentialsProvider(new UsernamePasswordCredentialsProvider(Token, ""))
                        .call()) {

                    new DirectoryServices().GetDirectoryData(baseFrame.getJTable1());

                    java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(CreateRepoPanel.this);
                    if (window != null) {
                        window.dispose();
                    }
                }
                return null;

            }

            @Override
            public void done() {
                try {
                    get(); // surfaces any exception thrown in doInBackground
                    GitProgressBar.setString("Clone Completed");
                    new DirectoryServices().GetDirectoryData(baseFrame.getJTable1());
                } catch (Exception ex) {
//                    ex.printStackTrace();
                    if (ex.getMessage().contains("git failed")) {
                        JOptionPane.showMessageDialog(jLabel1, "Error Cloning Git", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(jLabel1, "Error", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

        };

        worker.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GitProgressBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GitProgressBarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_GitProgressBarStateChanged

    private void TokenTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TokenTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TokenTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CommandTxtField;
    private javax.swing.JProgressBar GitProgressBar;
    private javax.swing.JTextField RepoNameTxtField;
    private javax.swing.JTextField TokenTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
