/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.toolkit.toolers;

import com.formdev.flatlaf.FlatLightLaf;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariel
 */
public class Toolers extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Toolers.class.getName());

    public String newFile(String filePath) {
        String strFilePath;
        String strFileName;

        try {

            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

            FileOutputStream fos = new FileOutputStream(filePath);

        } catch (Exception e) {
            System.out.println("Exception Occured");
        }

        return "";

    }

    /**
     * Creates new form Index
     */
    public Toolers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        SetupDirectory = new javax.swing.JLabel();
        ProceedBtn = new javax.swing.JButton();
        SetupDirectoryPath = new javax.swing.JTextField();
        MainLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(169, 211, 255));

        SetupDirectory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SetupDirectory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SetupDirectory.setText("Please set up directory:");

        ProceedBtn.setText("Proceed");
        ProceedBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ProceedBtn.setBorderPainted(false);
        ProceedBtn.addActionListener(this::ProceedBtnActionPerformed);

        SetupDirectoryPath.setText("C:\\Users\\Ariel\\Toolers\\");
            SetupDirectoryPath.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            SetupDirectoryPath.setName("FilePath"); // NOI18N
            SetupDirectoryPath.addActionListener(this::SetupDirectoryPathActionPerformed);

            MainLogo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
            MainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            MainLogo.setIcon(new javax.swing.ImageIcon("D:\\Users\\Ariel\\Documents\\NetBeansProjects\\Toolers\\src\\main\\java\\com\\toolkit\\toolers\\images\\folder.png")); // NOI18N
            MainLogo.setText("TOOLERS V1.0");
            MainLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            MainLogo.setFocusCycleRoot(true);
            MainLogo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(SetupDirectoryPath, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(ProceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(67, Short.MAX_VALUE))
                .addComponent(SetupDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(MainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(SetupDirectory)
                    .addGap(18, 18, 18)
                    .addComponent(SetupDirectoryPath, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ProceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(127, Short.MAX_VALUE))
            );

            SetupDirectoryPath.getAccessibleContext().setAccessibleName("");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void ProceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedBtnActionPerformed
        // TODO add your handling code here:
        String filePath = this.SetupDirectoryPath.getText();

        File targetDir = new File(filePath);

        if (targetDir.exists()) {
            System.err.println("Directory Exists!");
            JOptionPane.showMessageDialog(jPanel2, "Directory Exists!", "Error", JOptionPane.ERROR_MESSAGE);
            new Toolers().setVisible(false);
            new BaseFrame().setVisible(true);
            this.dispose();
        }

        boolean directoryCreated = targetDir.mkdir();

        if (directoryCreated) {
            System.out.println("directory created");
        }
        try {
            targetDir.createNewFile();
        } catch (IOException ex) {
            System.getLogger(Toolers.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_ProceedBtnActionPerformed

    private void SetupDirectoryPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetupDirectoryPathActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SetupDirectoryPathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        FlatLightLaf.setup();
        // for config themes
        // or: FlatDarkLaf.setup();
        // or: FlatIntelliJLaf.setup();
        // or: FlatDarculaLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Toolers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLogo;
    private javax.swing.JButton ProceedBtn;
    private javax.swing.JLabel SetupDirectory;
    private javax.swing.JTextField SetupDirectoryPath;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
